#define HYP_VERSION_MAJOR "1"
#define HYP_VERSION_MINOR "0"
#define HYP_VERSION_MICRO "0"
#define HYP_VERSION HYP_VERSION_MAJOR "." HYP_VERSION_MINOR "." HYP_VERSION_MICRO

#define HYP_RELEASE_YEAR "2017"
#define HYP_RELEASE_DATE "30-Jul-" HYP_RELEASE_YEAR

#define HYPVIEW_VERSION_MAJOR "1"
#define HYPVIEW_VERSION_MINOR "0"
#define HYPVIEW_VERSION_MICRO "0"
#define HYPVIEW_VERSION HYPVIEW_VERSION_MAJOR "." HYPVIEW_VERSION_MINOR "." HYPVIEW_VERSION_MICRO

/* UTF-8 of \u00a9 */
#define S_COPYRIGHT_SIGN "\xC2\xA9"

#define HYP_COPYRIGHT "Copyright " S_COPYRIGHT_SIGN " 1991-" HYP_RELEASE_YEAR " by Thorsten Otto"
#define HYP_URL       "http://www.tho-otto.de/"
#undef PACKAGE_URL
#define PACKAGE_URL HYP_URL
